# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  convers-evaluator-annotator:
    volumes:
      - "./annotators/ConversationEvaluator:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8004:8004
  spacy-nounphrases:
    volumes:
      - "./annotators/spacy_nounphrases:/src"
    ports:
      - 8006:8006
  dff-program-y:
    volumes:
      - "./skills/dff_program_y:/src"
      - "./common:/src/common"
    ports:
      - 8008:8008
  personality-catcher:
    volumes:
      - "./skills/personality_catcher:/app"
    ports:
      - 8010:8010
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  convers-evaluation-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  sentrewrite:
    volumes:
      - "./annotators/SentRewrite:/src"
    ports:
      - 8017:8017
  intent-responder:
    volumes:
      - "./skills/IntentResponder:/src"
      - "./common:/src/common"
    ports:
      - 8012:8012
  intent-catcher:
    volumes:
      - "./annotators/IntentCatcher/src:/src"
      - "./common:/src/common"
    ports:
      - 8014:8014
  badlisted-words:
    volumes:
      - "./annotators/BadlistedWordsDetector:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  dff-program-y-dangerous:
    volumes:
      - "./skills/dff_program_y_dangerous:/src"
      - "./common:/src/common"
    ports:
      - 8022:8022
  dff-movie-skill:
    volumes:
      - "./common:/src/common"
      - "./skills/dff_movie_skill:/src"
    ports:
      - 8023:8023
  ner:
    volumes:
      - './annotators/NER:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8021:8021
  eliza:
    volumes:
      - "./skills/eliza:/src"
    ports:
      - 8047:8047
  convert-reddit:
    volumes:
      - "./skills/convert_reddit:/app"
      - "./common:/src/common"
    ports:
      - 8029:8029
  personal-info-skill:
    volumes:
      - "./skills/personal_info_skill:/src"
      - "./common:/src/common"
    ports:
      - 8030:8030
  asr:
    volumes:
      - "./annotators/asr:/src"
      - "./common:/src/common"
    ports:
      - 8031:8031
  misheard-asr:
    volumes:
      - "./skills/misheard_asr:/src"
      - "./common:/src/common"
    ports:
      - 8033:8033
  dff-book-sfc-skill:
    volumes:
      - "./skills/dff_book_sfc_skill:/src"
      - "./common:/src/common"
    ports:
      - 8034:8034
  emotion-skill:
    volumes:
      - "./skills/emotion_skill:/src"
      - "./common:/src/common"
    ports:
      - 8049:8049
  dummy-skill-dialog:
    volumes:
      - "./skills/dummy_skill_dialog:/app"
    ports:
      - 8052:8052
  comet-atomic:
    volumes:
      - "./annotators/COMeT:/src"
      - "./common:/src/common"
    ports:
      - 8053:8053
  comet-conceptnet:
    volumes:
      - "./annotators/COMeT:/src"
      - "./common:/src/common"
    ports:
      - 8065:8065
  meta-script-skill:
    volumes:
      - "./skills/meta_script_skill:/src"
      - "./common:/src/common"
    ports:
      - 8054:8054
  small-talk-skill:
    volumes:
      - "./skills/small_talk_skill:/src"
      - "./common:/src/common"
    ports:
      - 8062:8062
  game-cooperative-skill:
    volumes:
      - "./skills/game_cooperative_skill:/src"
      - "./common:/src/common"
    ports:
      - 8068:8068
  dff-program-y-wide:
    volumes:
      - "./skills/dff_program_y_wide:/src"
      - "./common:/src/common"
    ports:
      - 8064:8064
  news-api-skill:
    volumes:
      - "./skills/news_api_skill:/src"
      - "./common:/src/common"
    ports:
      - 8066:8066
  news-api-annotator:
    volumes:
      - "./annotators/news_api:/src"
      - "./common:/src/common"
    ports:
      - 8112:8112
  factoid-qa:
    volumes:
      - "./skills/factoid_qa:/src"
      - "./common:/src/common"
    ports:
      - 8071:8071
  kbqa:
    volumes:
      - "./annotators/kbqa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8072:8072
  entity-linking:
    volumes:
      - "./annotators/entity_linking:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8075:8075
  wiki-parser:
    volumes:
      - "./annotators/wiki_parser:/src"
      - "./common:/src/common"
    ports:
      - 8077:8077
  mongo:
    ports:
      - 27017:27017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  spelling-preprocessing:
    volumes:
      - "./annotators/spelling_preprocessing:/src"
    ports:
      - 8074:8074
  dff-grounding-skill:
    volumes:
      - "./skills/dff_grounding_skill:/src"
      - "./common:/src/common"
    ports:
      - 8080:8080
  text-qa:
    volumes:
      - "./services/text_qa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8078:8078
  knowledge-grounding:
    volumes:
      - "./services/knowledge_grounding:/src"
    ports:
      - 8083:8083
  knowledge-grounding-skill:
    volumes:
      - "./common:/src/common"
      - "./skills/knowledge_grounding_skill:/src"
    ports:
      - 8085:8085

  dff-gaming-skill:
    volumes:
      - "./skills/dff_gaming_skill:/src"
      - "./common:/src/common"
    ports:
      - 8115:8115
  dff-friendship-skill:
    volumes:
      - "./skills/dff_friendship_skill:/src"
      - "./common:/src/common"
    ports:
      - 8086:8086
  masked-lm:
    volumes:
      - "./services/masked_lm:/src"
    ports:
      - 8088:8088
  entity-storer:
    volumes:
      - "./common:/src/common"
      - "./annotators/entity_storer:/src"
    ports:
      - 8089:8089
  dff-animals-skill:
    volumes:
      - "./skills/dff_animals_skill:/src"
      - "./common:/src/common"
    ports:
      - 8094:8094
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
    ports:
      - 8087:8087
  midas-classification:
    volumes:
      - "./annotators/midas_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8090:8090
  dff-travel-skill:
    volumes:
      - "./skills/dff_travel_skill:/src"
      - "./common:/src/common"
    ports:
      - 8096:8096
  dff-food-skill:
    volumes:
      - "./skills/dff_food_skill:/src"
      - "./common:/src/common"
    ports:
      - 8097:8097
  dff-science-skill:
    volumes:
      - "./skills/dff_science_skill:/src"
      - "./common:/src/common"
    ports:
      - 8101:8101
  dff-music-skill:
    volumes:
      - "./skills/dff_music_skill:/src"
      - "./common:/src/common"
    ports:
      - 8099:8099
  dff-sport-skill:
    volumes:
      - "./skills/dff_sport_skill:/src"
      - "./common:/src/common"
    ports:
      - 8098:8098
  dff-gossip-skill:
    volumes:
      - "./skills/dff_gossip_skill:/src"
      - "./common:/src/common"
    ports:
      - 8109:8109
  fact-random:
    volumes:
      - "./annotators/fact_random:/src"
      - "./common:/src/common"
    ports:
      - 8119:8119
  fact-retrieval:
    volumes:
      - "./annotators/fact_retrieval:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "./common:/src/common"
    ports:
      - 8100:8100
  hypothesis-scorer:
    volumes:
      - "./annotators/hypothesis_scorer:/src"
    ports:
      - 8110:8110
  dff-funfact-skill:
    volumes:
      - "./skills/dff_funfact_skill:/src"
      - "./common:/src/common"
    ports:
      - 8104:8104
  dff-bot-persona-skill:
    volumes:
      - "./skills/dff_bot_persona_skill:/src"
      - "./common:/src/common"
    ports:
      - 8105:8105
  dff-wiki-skill:
    volumes:
      - "./skills/dff_wiki_skill:/src"
      - "./common:/src/common"
    ports:
      - 8111:8111
  topic-recommendation:
    volumes:
      - "./annotators/topic_recommendation:/src"            
    ports:
      - 8113:8113
  user-persona-extractor:
    volumes:
      - "./annotators/user_persona_extractor:/src"
      - "./common:/src/common"
    ports:
      - 8114:8114
  wiki-facts:
    volumes:
      - "./services/wiki_facts:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8116:8116
  dff-art-skill:
    volumes:
      - "./skills/dff_art_skill:/src"
      - "./common:/src/common"
    ports:
      - 8117:8117
  entity-detection:
    volumes:
      - "./annotators/entity_detection:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8103:8103
  dff-coronavirus-skill:
    volumes:
      - "./skills/dff_coronavirus_skill:/src"
      - "./common:/src/common"
    ports:
      - 8061:8061
  dff-short-story-skill:
    volumes:
      - "./skills/dff_short_story_skill:/src"
      - "./common:/src/common"
    ports:
      - 8057:8057
  dff-weather-skill:
    volumes:
      - "./skills/dff_weather_skill:/src"
      - "./common:/src/common"
    ports:
      - 8037:8037
  dff-template-skill:
    volumes:
      - "./skills/dff_template_skill:/src"
      - "./common:/src/common"
    ports:
      - 8120:8120
  speech-function-classifier:
    volumes:
      - "./annotators/speech_function_classifier:/src"
      - "./common:/src/common"
    ports:
      - 8108:8108
  speech-function-predictor:
    volumes:
      - "./annotators/speech_function_predictor:/src"
      - "./common:/src/common"
    ports:
      - 8107:8107
version: "3.7"
